# Используем образ Python 3.10 slim
FROM python:3.10-slim

# Устанавливаем зависимости
RUN apt-get update && apt-get install -y netcat
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY . .

# Задаем переменную окружения DATABASE_URL
ENV DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres

# Запускаем миграции
CMD sh -c "python manage.py wait_for_db && python manage.py migrate"
